### ISSUE TITLE
Error: Cannot find module 'strftime'

### ISSUE THREAD

**Issue by nk222** [samsonjs/strftime#67] opened 2015-07-15 08:22 UTC
it seems like i cannot instal strftime globally using 

npm install -g strftime

it works however when i install it locally. What could be the reason?

**Comment by alexandrnikitin** [comment] 2015-07-16 08:29
It works for me. What's `npm version`?

**Comment by nk222** [comment] 2015-07-16 12:45
npm: '2.11.3',
modules: '14',
node: '0.12.7',

The install with -g option works fine. Just when I try to use the package with require('strftime') i get the error: Cannot find module 'strftime'

**Comment by alexandrnikitin** [comment] 2015-08-17 08:59
@nk222,
Have you solved your issue? 
Probably you don't need to install `strftime` globally. `strftime` doesn't provide CLI so there's no need to have it globally. 
Basically your have two ways to manage packages in your project.
1. Install them locally using `npm install strftime`
2. Add them to `package.json` file as dependencies and then `npm install` to install all listed packages.
There's one more option to link the global package to local one using `npm link strftime`. But i don't quite like it.
Did it help?

**Comment by alexandrnikitin** [comment] 2015-08-21 08:06
I'm closing the issue. Feel free to reopen if the problem isn't solved.

**Closed by alexandrnikitin** 2015-08-21 08:06 UTC

**Comment by nk222** [comment] 2015-08-21 08:10
Thanks! I just installed it locally and everything was fine ;)
